import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'
import TopBar from '@/components/topBar'
import Container from '@/components/container'
import PageBody from '@/components/pageBody'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <PageBody>
          <h1 className="text-lg font-bold">Test</h1>
          <p className="my-2">
            This is a site to dump miscellaneous things in. 
            Right now, some of those things are some endpoints to generate useful tabletop RPG data, a WIP digital cookbook, and a resume.
          </p>
          <p className="my-2">Foo.</p>
        </PageBody>
      </Container>
      {/* <div><h1 className="text-center">Matthew's Site</h1></div>
      <Link href="/recipes">recipes</Link>
      <Link href="/resume">resume</Link>
      <Link href="/foo">foo</Link> */}
    </>
  )
}
